import { Card } from '@/components';
import { Response } from '@/ts';
import Head from 'next/head';
import { useEffect, useState } from 'react';

interface HomeProps {
  information: Response;
}

const Home: React.FC<HomeProps> = ({ information }) => {
  const [clientData, setClientData] = useState<Response>({} as Response);
  useEffect(() => {
    getClientData();
  }, []);

  const getClientData = async () => {
    try {
      const request = await fetch(
        'https://kwm6eoos53.execute-api.us-east-1.amazonaws.com/prod/results',
      );
      const data = await request.json();
      const information = JSON.parse(data.body).contents[0].data;

      setClientData(information);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className='container-xl mx-auto py-5'>
        <p>SSR</p>
        <Card data={information} />
        <p>CSR</p>
        <Card data={clientData} />
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  try {
    const request = await fetch(
      'https://kwm6eoos53.execute-api.us-east-1.amazonaws.com/prod/results',
    );
    const data = await request.json();
    const information = JSON.parse(data.body).contents[0].data;

    return {
      props: {
        information,
      },
    };
  } catch (error) {
    console.log(error);

    return {
      props: {
        information: {},
      },
    };
  }
};

export default Home;
